services:
    odiseo_sylius_report_plugin.data_fetcher.data:
        class: Odiseo\SyliusReportPlugin\DataFetcher\Data

    odiseo_sylius_report_plugin.data_fetcher:
        class: Odiseo\SyliusReportPlugin\DataFetcher\DelegatingDataFetcher
        public: true
        arguments:
            - '@odiseo_sylius_report_plugin.registry.data_fetcher'

    odiseo_sylius_report_plugin.data_fetcher.user_registration:
        class: Odiseo\SyliusReportPlugin\DataFetcher\UserRegistrationDataFetcher
        arguments:
            - '%sylius.model.shop_user.class%'
            - '@odiseo_sylius_report_plugin.filter.query_filter'
            - '@odiseo_sylius_report_plugin.data_fetcher.data'
        tags:
            - { name: odiseo_sylius_report_plugin.data_fetcher, fetcher: odiseo_sylius_report_plugin_data_fetcher_user_registration, label: "odiseo_sylius_report_plugin.data_fetcher.user_registration" }

    odiseo_sylius_report_plugin.data_fetcher.sales_total:
        class: Odiseo\SyliusReportPlugin\DataFetcher\SalesTotalDataFetcher
        arguments:
            - '%sylius.model.order.class%'
            - '@odiseo_sylius_report_plugin.filter.query_filter'
            - '@odiseo_sylius_report_plugin.data_fetcher.data'
        tags:
            - { name: odiseo_sylius_report_plugin.data_fetcher, fetcher: odiseo_sylius_report_plugin_data_fetcher_sales_total, label: "odiseo_sylius_report_plugin.data_fetcher.sales_total" }

    odiseo_sylius_report_plugin.data_fetcher.number_of_orders:
        class: Odiseo\SyliusReportPlugin\DataFetcher\NumberOfOrdersDataFetcher
        arguments:
            - '%sylius.model.order.class%'
            - '@odiseo_sylius_report_plugin.filter.query_filter'
            - '@odiseo_sylius_report_plugin.data_fetcher.data'
        tags:
            - { name: odiseo_sylius_report_plugin.data_fetcher, fetcher: odiseo_sylius_report_plugin_data_fetcher_number_of_orders, label: "odiseo_sylius_report_plugin.data_fetcher.number_of_orders" }
